# Generated by Django 3.1a1 on 2020-05-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200526_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='discription',
            new_name='description',
        ),
    ]
