# Generated by Django 3.1a1 on 2020-05-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirm', 'confirm'), ('cancel', 'cancel')], default='pending', max_length=10)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
